/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.emailsender.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Template service. Represents a row in the &quot;RL_Template&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.emailsender.model.impl.TemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.emailsender.model.impl.TemplateImpl}.
 * </p>
 *
 * @author lorenzorodriguez
 * @see Template
 * @see com.rivetlogic.emailsender.model.impl.TemplateImpl
 * @see com.rivetlogic.emailsender.model.impl.TemplateModelImpl
 * @generated
 */
public interface TemplateModel extends BaseModel<Template>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a template model instance should use the {@link Template} interface instead.
	 */

	/**
	 * Returns the primary key of this template.
	 *
	 * @return the primary key of this template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this template.
	 *
	 * @param primaryKey the primary key of this template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this template.
	 *
	 * @return the uuid of this template
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this template.
	 *
	 * @param uuid the uuid of this template
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the template ID of this template.
	 *
	 * @return the template ID of this template
	 */
	public long getTemplateId();

	/**
	 * Sets the template ID of this template.
	 *
	 * @param templateId the template ID of this template
	 */
	public void setTemplateId(long templateId);

	/**
	 * Returns the group ID of this template.
	 *
	 * @return the group ID of this template
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this template.
	 *
	 * @param groupId the group ID of this template
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this template.
	 *
	 * @return the company ID of this template
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this template.
	 *
	 * @param companyId the company ID of this template
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this template.
	 *
	 * @return the user ID of this template
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this template.
	 *
	 * @param userId the user ID of this template
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this template.
	 *
	 * @return the user uuid of this template
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this template.
	 *
	 * @param userUuid the user uuid of this template
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this template.
	 *
	 * @return the user name of this template
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this template.
	 *
	 * @param userName the user name of this template
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this template.
	 *
	 * @return the create date of this template
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this template.
	 *
	 * @param createDate the create date of this template
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this template.
	 *
	 * @return the modified date of this template
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this template.
	 *
	 * @param modifiedDate the modified date of this template
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this template.
	 *
	 * @return the name of this template
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this template.
	 *
	 * @param name the name of this template
	 */
	public void setName(String name);

	/**
	 * Returns the value of this template.
	 *
	 * @return the value of this template
	 */
	public String getValue();

	/**
	 * Sets the value of this template.
	 *
	 * @param value the value of this template
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rivetlogic.emailsender.model.Template template);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rivetlogic.emailsender.model.Template> toCacheModel();

	@Override
	public com.rivetlogic.emailsender.model.Template toEscapedModel();

	@Override
	public com.rivetlogic.emailsender.model.Template toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}